#!/usr/bin/env bash
#
# Test runner for /mind/edges/list
#
set -e

BRANE_ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
source "$BRANE_ROOT/tests/lib.sh"

INPUT=$(cat)
workspace

case "$TC_CASE_NAME" in
  00-success-list-all)
    init_mind
    create_concepts '[{"name": "A", "type": "Entity"}, {"name": "B", "type": "Entity"}, {"name": "C", "type": "Entity"}]'
    create_edges '[{"source": 1, "target": 2, "relation": "DEPENDS_ON"}, {"source": 2, "target": 3, "relation": "CONFLICTS_WITH"}]'
    ;;
  01-success-list-empty)
    init_mind
    ;;
  02-success-filter-source)
    init_mind
    create_concepts '[{"name": "A", "type": "Entity"}, {"name": "B", "type": "Entity"}, {"name": "C", "type": "Entity"}]'
    create_edges '[{"source": 1, "target": 2, "relation": "DEPENDS_ON"}, {"source": 1, "target": 3, "relation": "DEPENDS_ON"}, {"source": 2, "target": 3, "relation": "CONFLICTS_WITH"}]'
    ;;
  03-success-filter-target)
    init_mind
    create_concepts '[{"name": "A", "type": "Entity"}, {"name": "B", "type": "Entity"}, {"name": "C", "type": "Entity"}]'
    create_edges '[{"source": 1, "target": 3, "relation": "DEPENDS_ON"}, {"source": 2, "target": 3, "relation": "CONFLICTS_WITH"}, {"source": 1, "target": 2, "relation": "DEFINED_IN"}]'
    ;;
  04-success-filter-relation)
    init_mind
    create_concepts '[{"name": "A", "type": "Entity"}, {"name": "B", "type": "Entity"}, {"name": "C", "type": "Entity"}]'
    create_edges '[{"source": 1, "target": 2, "relation": "DEPENDS_ON"}, {"source": 2, "target": 3, "relation": "DEPENDS_ON"}, {"source": 1, "target": 3, "relation": "CONFLICTS_WITH"}]'
    ;;
esac

echo "$INPUT" | brane /mind/edges/list
